djangochallenge/djangochallenge/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import user.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', user.views.home, name='home'),
    url(r'^user/', include('user.urls'))
]

djangochallenge/user/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # user/list - List all users
    url(r'^list$', views.IndexView.as_view(), name='index'),
    # Create a user - /user/add
    url(r'^add/$', views.UserCreate.as_view(), name='user-add')
]

djangochallenge/user/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class User(models.Model) :
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    FEMALE = '0'
    MALE = '1'
    GENDER = ((FEMALE, 'Female'), (MALE, 'Male'))
    gender = models.CharField(max_length = 1, choices = GENDER, default = FEMALE)

    # Url to redirects to the list page after creating a User
    def get_absolute_url(self):
        return reverse('user:index')

    # def __str__(self):
    #     return self.full_name + ' ' + self.email

djangochallenge/user/views.py
from django.views import generic
from django.shortcuts import render_to_response
from django.views.generic.edit import CreateView
from .models import User

# Create your home view
def home(request) :
    return render_to_response('user/home.html')

class IndexView(generic.ListView) :
    template_name = 'user/index.html'
    context_object_name = 'users' # default = 'object_list'
    def get_queryset(self):
        return User.objects.all()

class UserCreate(CreateView) :
    model = User # Model to create
    # Specify fields to add
    fields = ['full_name', 'email', 'gender']

djangochallenge/user/templates/user/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Django Challenge Home{% endblock %}</title>
<link href="{% static 'user/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<!--theme-style-->
<link href="{% static 'user/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="User, Data, List, Django, Python" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--theme-style-->
<link href="{% static 'user/css/style4.css' %}" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
<div class="header">
<div class="container">
		<div class="head">
			<div class=" logo">
				<a href="/"><img src="{% static 'user/images/logo.png' %}" alt="logo"></a>
			</div>
		</div>
	</div>
	<div class="header-top">
		<div class="container">


				<div class="clearfix"> </div>
		</div>
		</div>

		<div class="container">

			<div class="head-top">

		 <div class="col-sm-8 col-md-offset-2 h_menu4">
				<nav class="navbar nav_bottom" role="navigation">

 <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header nav_2">
      <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

   </div>
   <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
        <ul class="nav navbar-nav nav_1">
            <li><a class="color" href="/">Home</a></li>
            <li><a class="color6" href="{% url 'user:index' %}">List Users</a></li>
			<li><a class="color6" href="{% url 'user:user-add' %}">Add Users</a></li>
        </ul>
     </div><!-- /.navbar-collapse -->

</nav>
			</div>

			<div class="clearfix"></div>
		</div>
	</div>
</div>

{% block body %}
{% endblock %}

    <!--//footer-->
    <div class="footer">
        <div class="footer-bottom">
            <div class="container">
                <p class="footer-class">&copy; 2016 DjangoChallenge. All Rights Reserved | By <a href="#">Elvis</a> </p>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!--//footer-->

<script src="{% static 'user/js/jquery.min.js' %}"></script>
<script src="{% static 'user/js/bootstrap.min.js' %}"></script>
</body>
</html>

djangochallenge/user/templates/user/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label for="" class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

djangochallenge/user/templates/user/home.html
{% extends 'user/base.html' %}
{% block body %}
    <div class="banner">
        <div class="container">
            <section class="rw-wrapper">
                <h1 class="rw-sentence">
                    <span>Users &amp; Data</span>
                    <div class="rw-words rw-words-1">
                        <span>&nbsp; Filter</span>
                        <span>&nbsp; Filter</span>
                        <span>&nbsp; Filter</span>
                    </div>
                    <div class="rw-words rw-words-2">
                        <span>First Django Test</span>
                        <span>Cool!</span>
                        <span>First Django Test</span>
                        <span>Cool!</span>
                        <span>First Django Test</span>
                        <span>Cool!</span>
                    </div>
                </h1>
            </section>
        </div>
    </div>
{% endblock %}

djangochallenge/user/templates/user/index.html
{% extends 'user/base.html' %}
{% load staticfiles %}
{% block body %}
    <!--banner-->
<div class="banner-top">
	<div class="container">
		<h1>List</h1>
		<em></em>
		<h2><a href="index.html">Home</a><label>/</label>List Users</a></h2>
	</div>
</div>
<div class="container" style="min-height: 430px">
	<div class="check-out">
	<div class="bs-example4" data-example-id="simple-responsive-table">
    <div class="table-responsive">
    	    <table class="table-heading simpleCart_shelfItem">
		  <tr>
			<th class="table-grid">Users</th>

			<th>Name</th>
			<th>Email Address </th>

		  </tr>
            {% if users %}
                {% for user in users %}
                    <tr class="cart-header">

                    <td class="ring-in"><a href="#" class="at-in"><img src="{% static 'user/images' %}/{% if user.gender == '1' %}ch2{% else %}ch{% endif %}.jpg" class="img-responsive" alt=""></a>
                    <div class="sed">
                        {% if user.gender == '1' %}Male{% else %}Female{% endif %}
                    </div>
                    </td>
                    <td>{{ user.full_name }}</td>
                    <td>{{ user.email }}</td>
                  </tr>
                {% endfor %}
            {% else %}
                <tr><td colspan="3">No users yet!</td></tr>
            {% endif %}
	</table>
	</div>
	</div>
	<div class="produced">
	<a href="{% url 'user:user-add' %}" class="hvr-skew-backward">Add More +</a> <br />
	 </div>
    </div>
</div>
{% endblock %}

djangochallenge/user/templates/user/user_form.html
{% extends 'user/base.html' %}
{% block title %}Create New User{% endblock %}
{% block body %}
<!--banner-->
<div class="banner-top">
	<div class="container">
		<h1>Add</h1>
		<em></em>
		<h2><a href="/">Home</a><label>/</label>Add Users</a></h2>
	</div>
</div>
<!--login-->
<div class="container" style="min-height: 430px">
		<div class="login">
			<form action="" method="post">
            {% csrf_token %}
                <div class="col-md-offset-3 col-md-6 login-do">
                    {% include 'user/form_template.html' %}

                    <label class="hvr-skew-backward">
                        <input type="submit" value="Submit">
                    </label>

                </div>
			</form>
		</div>

</div>
{% endblock %}